# Generated by Django 6.0.3 on 2026-03-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='finished_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
