# Generated by Django 6.0.1 on 2026-03-30 16:33

import django.db.models.deletion
from django.db import migrations, models


def clear_invalid_choice_references(apps, schema_editor):
    Question = apps.get_model('main', 'Question')
    UserAnswer = apps.get_model('main', 'UserAnswer')
    Choice = apps.get_model('main', 'Choice')

    valid_choice_ids = set(Choice.objects.values_list('id', flat=True))

    for question in Question.objects.exclude(correct_choice_id__isnull=True):
        if question.correct_choice_id not in valid_choice_ids:
            question.correct_choice_id = None
            question.save(update_fields=['correct_choice_id'])

    for user_answer in UserAnswer.objects.exclude(selected_choice_id__isnull=True):
        if user_answer.selected_choice_id not in valid_choice_ids:
            user_answer.selected_choice_id = None
            user_answer.save(update_fields=['selected_choice_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usertest_finished_at_alter_usertest_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(clear_invalid_choice_references, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='question',
            old_name='correct_choice_id',
            new_name='correct_choice',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='selected_choice_id',
            new_name='selected_choice',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_for_questions', to='main.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answers', to='main.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
