# Generated by Django 6.0.3 on 2026-04-01 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_practiceexercise_practicechoice_userpracticeattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variantlar'},
        ),
        migrations.AlterModelOptions(
            name='essaytopic',
            options={'ordering': ('-is_featured', '-created_at'), 'verbose_name': 'Insho mavzusi', 'verbose_name_plural': 'Insho mavzulari'},
        ),
        migrations.AlterModelOptions(
            name='practicechoice',
            options={'verbose_name': 'Misol / Masala varianti', 'verbose_name_plural': 'Misol / Masala variantlari'},
        ),
        migrations.AlterModelOptions(
            name='practiceexercise',
            options={'ordering': ('-is_featured', '-created_at'), 'verbose_name': 'Misol / Masala', 'verbose_name_plural': 'Misol / Masalalar'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='subjectsectionentry',
            options={'ordering': ('order', '-is_featured', '-created_at'), 'verbose_name': "Fan bo'limi materiali", 'verbose_name_plural': "Fan bo'limi materiallari"},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-end_date', '-purchased_at'), 'verbose_name': 'Obuna', 'verbose_name_plural': 'Obunalar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Foydalanuvchi javobi', 'verbose_name_plural': 'Foydalanuvchi javoblari'},
        ),
        migrations.AlterModelOptions(
            name='userpracticeattempt',
            options={'ordering': ('-created_at',), 'verbose_name': 'Misol / Masala urinish', 'verbose_name_plural': 'Misol / Masala urinishlari'},
        ),
        migrations.AlterModelOptions(
            name='usertest',
            options={'verbose_name': 'Test urinish', 'verbose_name_plural': 'Test urinishlari'},
        ),
        migrations.CreateModel(
            name='PracticeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_book', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('S', 'S'), ('S+', 'S+'), ('B', 'B'), ('B+', 'B+'), ('A', 'A'), ('A+', 'A+')], default='S', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
            options={
                'verbose_name': "Misol / Masala bo'limi",
                'verbose_name_plural': "Misol / Masala bo'limlari",
                'ordering': ('-is_featured', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='practiceexercise',
            name='practice_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='main.practiceset'),
        ),
        migrations.CreateModel(
            name='PracticeSetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.practiceset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Misol / Masala bo'limi urinish",
                'verbose_name_plural': "Misol / Masala bo'limi urinishlari",
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='userpracticeattempt',
            name='practice_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.practicesetattempt'),
        ),
    ]
