# Generated by Django 6.0.3 on 2026-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_book_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceexercise',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
