# Generated by Django 6.0.3 on 2026-04-01 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_practiceexercise_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubjectPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_level', models.CharField(choices=[('S', 'S'), ('S+', 'S+'), ('B', 'B'), ('B+', 'B+'), ('A', 'A'), ('A+', 'A+')], default='S', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi fan sozlamasi',
                'verbose_name_plural': 'Foydalanuvchi fan sozlamalari',
                'constraints': [models.UniqueConstraint(fields=('user', 'subject'), name='unique_user_subject_preference')],
            },
        ),
    ]
