# Generated by Django 6.0.3 on 2026-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_book_access_level_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsectionentry',
            name='usage_note',
            field=models.TextField(blank=True),
        ),
    ]
