# Generated by Django 6.0.3 on 2026-04-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user_stats(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    UserTest = apps.get_model("main", "UserTest")
    UserPracticeAttempt = apps.get_model("main", "UserPracticeAttempt")
    PracticeSetAttempt = apps.get_model("main", "PracticeSetAttempt")
    UserStatSummary = apps.get_model("main", "UserStatSummary")
    UserSubjectStat = apps.get_model("main", "UserSubjectStat")

    XP_PER_CORRECT_TEST_ANSWER = 6
    XP_PER_CORRECT_PRACTICE_ANSWER = 5

    for user in User.objects.all().iterator():
        user_tests = list(
            UserTest.objects.filter(user=user)
            .select_related("test")
            .order_by("-finished_at", "-started_at", "-id")
        )
        practice_sessions = list(
            PracticeSetAttempt.objects.filter(user=user)
            .select_related("practice_set", "practice_set__subject")
            .order_by("-created_at", "-id")
        )
        practice_attempts = list(
            UserPracticeAttempt.objects.filter(user=user)
            .select_related("exercise", "exercise__subject", "practice_session")
            .order_by("-created_at", "-id")
        )

        total_correct_test_answers = sum(max(0, attempt.correct_count or 0) for attempt in user_tests)
        total_correct_practice_answers = sum(1 for attempt in practice_attempts if attempt.is_correct)
        test_xp = total_correct_test_answers * XP_PER_CORRECT_TEST_ANSWER
        practice_xp = total_correct_practice_answers * XP_PER_CORRECT_PRACTICE_ANSWER
        best_test_score = max((attempt.score or 0 for attempt in user_tests), default=0)
        session_best_practice = max((attempt.score or 0 for attempt in practice_sessions), default=0)
        single_best_practice = 100 if any(attempt.is_correct for attempt in practice_attempts if attempt.practice_session_id is None) else 0
        last_activity_candidates = [
            attempt.finished_at or attempt.started_at
            for attempt in user_tests
            if attempt.finished_at or attempt.started_at
        ]
        last_activity_candidates.extend(attempt.created_at for attempt in practice_sessions if attempt.created_at)
        last_activity_candidates.extend(attempt.created_at for attempt in practice_attempts if attempt.created_at)
        last_activity_at = max(last_activity_candidates, default=None)

        UserStatSummary.objects.update_or_create(
            user=user,
            defaults={
                "lifetime_xp": test_xp + practice_xp,
                "lifetime_test_count": len(user_tests),
                "lifetime_practice_count": len(practice_attempts),
                "total_correct_answers": total_correct_test_answers + total_correct_practice_answers,
                "total_correct_test_answers": total_correct_test_answers,
                "total_correct_practice_answers": total_correct_practice_answers,
                "best_test_score": best_test_score,
                "best_practice_score": max(session_best_practice, single_best_practice),
                "last_activity_at": last_activity_at,
            },
        )

        subject_stats = {}
        for attempt in user_tests:
            subject_id = attempt.test.subject_id
            stats = subject_stats.setdefault(
                subject_id,
                {
                    "xp": 0,
                    "tests_taken": 0,
                    "practice_taken": 0,
                    "total_correct_test_answers": 0,
                    "total_correct_practice_answers": 0,
                    "best_score": 0,
                    "last_activity_at": None,
                },
            )
            stats["tests_taken"] += 1
            stats["total_correct_test_answers"] += max(0, attempt.correct_count or 0)
            stats["xp"] += max(0, attempt.correct_count or 0) * XP_PER_CORRECT_TEST_ANSWER
            stats["best_score"] = max(stats["best_score"], attempt.score or 0)
            attempt_time = attempt.finished_at or attempt.started_at
            if attempt_time and (stats["last_activity_at"] is None or attempt_time > stats["last_activity_at"]):
                stats["last_activity_at"] = attempt_time

        for attempt in practice_attempts:
            subject_id = attempt.exercise.subject_id
            stats = subject_stats.setdefault(
                subject_id,
                {
                    "xp": 0,
                    "tests_taken": 0,
                    "practice_taken": 0,
                    "total_correct_test_answers": 0,
                    "total_correct_practice_answers": 0,
                    "best_score": 0,
                    "last_activity_at": None,
                },
            )
            stats["practice_taken"] += 1
            if attempt.is_correct:
                stats["total_correct_practice_answers"] += 1
                stats["xp"] += XP_PER_CORRECT_PRACTICE_ANSWER
                if attempt.practice_session_id is None:
                    stats["best_score"] = max(stats["best_score"], 100)
            if attempt.created_at and (stats["last_activity_at"] is None or attempt.created_at > stats["last_activity_at"]):
                stats["last_activity_at"] = attempt.created_at

        for session in practice_sessions:
            subject_id = session.practice_set.subject_id
            stats = subject_stats.setdefault(
                subject_id,
                {
                    "xp": 0,
                    "tests_taken": 0,
                    "practice_taken": 0,
                    "total_correct_test_answers": 0,
                    "total_correct_practice_answers": 0,
                    "best_score": 0,
                    "last_activity_at": None,
                },
            )
            stats["best_score"] = max(stats["best_score"], session.score or 0)
            if session.created_at and (stats["last_activity_at"] is None or session.created_at > stats["last_activity_at"]):
                stats["last_activity_at"] = session.created_at

        for subject_id, stats in subject_stats.items():
            total_correct_answers = stats["total_correct_test_answers"] + stats["total_correct_practice_answers"]
            UserSubjectStat.objects.update_or_create(
                user=user,
                subject_id=subject_id,
                defaults={
                    "xp": stats["xp"],
                    "tests_taken": stats["tests_taken"],
                    "practice_taken": stats["practice_taken"],
                    "total_correct_answers": total_correct_answers,
                    "total_correct_test_answers": stats["total_correct_test_answers"],
                    "total_correct_practice_answers": stats["total_correct_practice_answers"],
                    "best_score": stats["best_score"],
                    "last_activity_at": stats["last_activity_at"],
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_grammarlessonprogress_grammarlessonquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_xp', models.IntegerField(default=0)),
                ('lifetime_test_count', models.PositiveIntegerField(default=0)),
                ('lifetime_practice_count', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('total_correct_test_answers', models.PositiveIntegerField(default=0)),
                ('total_correct_practice_answers', models.PositiveIntegerField(default=0)),
                ('best_test_score', models.PositiveIntegerField(default=0)),
                ('best_practice_score', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi umumiy statistikasi',
                'verbose_name_plural': 'Foydalanuvchi umumiy statistikasi',
            },
        ),
        migrations.CreateModel(
            name='UserSubjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('tests_taken', models.PositiveIntegerField(default=0)),
                ('practice_taken', models.PositiveIntegerField(default=0)),
                ('total_correct_answers', models.PositiveIntegerField(default=0)),
                ('total_correct_test_answers', models.PositiveIntegerField(default=0)),
                ('total_correct_practice_answers', models.PositiveIntegerField(default=0)),
                ('best_score', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi fan statistikasi',
                'verbose_name_plural': 'Foydalanuvchi fan statistikasi',
            },
        ),
        migrations.AlterField(
            model_name='subjectsectionentry',
            name='section_key',
            field=models.CharField(choices=[('formulas', 'Formulalar'), ('problems', 'Misol / Masalalar'), ('terms', 'Atamalar'), ('chronology', 'Xronologiya'), ('grammar', 'Gramatika'), ('rules', 'Qoidalar'), ('essay', 'Insho'), ('extras', "Qo'shimcha ma'lumotlar"), ('events', 'Sanalar / Voqealar')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='practiceexercise',
            index=models.Index(fields=['practice_set', 'created_at'], name='main_pexpr_set_created_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceexercise',
            index=models.Index(fields=['subject', 'difficulty'], name='main_pexpr_subject_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesetattempt',
            index=models.Index(fields=['user', 'created_at'], name='main_pset_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesetattempt',
            index=models.Index(fields=['user', 'practice_set'], name='main_pset_user_set_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectsectionentry',
            index=models.Index(fields=['subject', 'section_key', 'order'], name='main_ssect_sub_sec_ord_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['user', 'question'], name='main_uans_user_question_idx'),
        ),
        migrations.AddIndex(
            model_name='userpracticeattempt',
            index=models.Index(fields=['user', 'created_at'], name='main_upra_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='userpracticeattempt',
            index=models.Index(fields=['user', 'practice_session'], name='main_upra_user_session_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['user', 'finished_at'], name='main_usert_user_finish_idx'),
        ),
        migrations.AddIndex(
            model_name='usertest',
            index=models.Index(fields=['user', 'test'], name='main_usert_user_test_idx'),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat_summary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersubjectstat',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='main.subject'),
        ),
        migrations.AddField(
            model_name='usersubjectstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userstatsummary',
            index=models.Index(fields=['lifetime_xp'], name='main_ustat_xp_idx'),
        ),
        migrations.AddIndex(
            model_name='userstatsummary',
            index=models.Index(fields=['last_activity_at'], name='main_ustat_last_act_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubjectstat',
            index=models.Index(fields=['user', 'subject'], name='main_usub_user_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubjectstat',
            index=models.Index(fields=['subject', 'xp'], name='main_usub_subject_xp_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubjectstat',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='unique_user_subject_stat'),
        ),
        migrations.RunPython(backfill_user_stats, noop_reverse),
    ]
