# Generated by Django 6.0.3 on 2026-04-05 18:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_subscription_plans_and_backfill(apps, schema_editor):
    Subscription = apps.get_model("main", "Subscription")
    SubscriptionPlan = apps.get_model("main", "SubscriptionPlan")
    UserSubscription = apps.get_model("main", "UserSubscription")
    UserSubscriptionSubject = apps.get_model("main", "UserSubscriptionSubject")
    Subject = apps.get_model("main", "Subject")

    plan_defs = [
        {"code": "single-subject", "name": "1 fan", "subject_limit": 1, "is_all_access": False, "price": 30000, "duration_days": 30},
        {"code": "double-subject", "name": "2 fan", "subject_limit": 2, "is_all_access": False, "price": 55000, "duration_days": 30},
        {"code": "triple-subject", "name": "3 fan", "subject_limit": 3, "is_all_access": False, "price": 75000, "duration_days": 30},
        {"code": "all-access", "name": "All access", "subject_limit": None, "is_all_access": True, "price": 90000, "duration_days": 30},
        {"code": "beta-trial-all-access", "name": "Beta trial", "subject_limit": None, "is_all_access": True, "price": 0, "duration_days": 14},
    ]
    plans = {}
    for item in plan_defs:
        plan, _ = SubscriptionPlan.objects.update_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "subject_limit": item["subject_limit"],
                "is_all_access": item["is_all_access"],
                "price": item["price"],
                "duration_days": item["duration_days"],
                "is_active": True,
            },
        )
        plans[item["code"]] = plan

    now = django.utils.timezone.now()
    all_subject_count = Subject.objects.count()
    subscriptions = (
        Subscription.objects.select_related("subject", "user")
        .order_by("user_id", "end_date", "purchased_at", "id")
    )

    grouped = {}
    for row in subscriptions.iterator():
        key = (row.user_id, row.end_date)
        grouped.setdefault(key, []).append(row)

    for (user_id, end_date), rows in grouped.items():
        subject_count = len(rows)
        plan = None
        if subject_count == 1:
            plan = plans["single-subject"]
        elif subject_count == 2:
            plan = plans["double-subject"]
        elif subject_count == 3:
            plan = plans["triple-subject"]
        elif all_subject_count and subject_count == all_subject_count:
            plan = None

        user_subscription = UserSubscription.objects.create(
            user_id=user_id,
            plan=plan,
            title=(plan.name if plan else f"Legacy import ({subject_count} fan)"),
            status="active" if end_date >= now else "expired",
            source="legacy_import",
            is_all_access=False,
            started_at=min((row.purchased_at for row in rows), default=end_date),
            end_at=end_date,
        )
        UserSubscriptionSubject.objects.bulk_create(
            [
                UserSubscriptionSubject(subscription=user_subscription, subject=row.subject)
                for row in rows
            ]
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_userstatsummary_usersubjectstat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subject_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_all_access', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ('price', 'name'),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Tugagan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20)),
                ('source', models.CharField(choices=[('purchase', 'Sotib olish'), ('beta_trial', 'Beta trial'), ('legacy_import', 'Legacy import'), ('manual', "Qo'lda")], default='purchase', max_length=20)),
                ('is_all_access', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='main.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi obunasi',
                'verbose_name_plural': 'Foydalanuvchi obunalari',
                'ordering': ('-end_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_items', to='main.subject')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='main.usersubscription')),
            ],
            options={
                'verbose_name': 'Obunadagi fan',
                'verbose_name_plural': 'Obunadagi fanlar',
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status', 'end_at'], name='main_usub_user_stat_end_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'created_at'], name='main_usub_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscriptionsubject',
            index=models.Index(fields=['subscription', 'subject'], name='main_usubj_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscriptionsubject',
            index=models.Index(fields=['subject'], name='main_usubj_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscriptionsubject',
            constraint=models.UniqueConstraint(fields=('subscription', 'subject'), name='unique_subscription_subject'),
        ),
        migrations.RunPython(seed_subscription_plans_and_backfill, noop_reverse),
    ]
