# Generated by Django 6.0.3 on 2026-04-06 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_subscriptionplan_usersubscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practiceset',
            options={'ordering': ('-is_featured', '-created_at'), 'verbose_name': 'Mashq', 'verbose_name_plural': 'Mashqlar'},
        ),
        migrations.AddField(
            model_name='grammarlessonprogress',
            name='xp_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='essay_xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='grammar_xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='practice_xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='test_xp_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='total_essay_topics_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatsummary',
            name='total_grammar_lessons_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EssayTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_rows', to='main.essaytopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Esse mavzu progressi',
                'verbose_name_plural': 'Esse mavzu progresslari',
                'constraints': [models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_essay_topic_progress')],
            },
        ),
    ]
