# Generated by Django 6.0.3 on 2026-04-12 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_s_levels_to_c_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essaytopic',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'Insho mavzusi', 'verbose_name_plural': 'Insho mavzulari'},
        ),
        migrations.AlterModelOptions(
            name='subjectsectionentry',
            options={'ordering': ('created_at', 'id'), 'verbose_name': "Fan bo'limi materiali", 'verbose_name_plural': "Fan bo'limi materiallari"},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ('display_order', 'price', 'name'), 'verbose_name': 'Obuna rejasi', 'verbose_name_plural': 'Obuna rejalari'},
        ),
        migrations.AddField(
            model_name='profile',
            name='free_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_profiles', to='main.subject'),
        ),
        migrations.AddField(
            model_name='profile',
            name='free_subject_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_advanced_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_advanced_stats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_full_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_mock_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_use_progress_recommendations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_ai_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_test_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stack_mode',
            field=models.CharField(choices=[('additive', "Qo'shiladigan"), ('replace', 'Almashtiradigan')], default='additive', max_length=20),
        ),
        migrations.CreateModel(
            name='UserDailyQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('tests_started', models.PositiveIntegerField(default=0)),
                ('ai_requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quota_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kunlik kvota',
                'verbose_name_plural': 'Kunlik kvotalar',
                'indexes': [models.Index(fields=['date'], name='main_udq_date_idx'), models.Index(fields=['user', 'date'], name='main_udq_user_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_quota_usage')],
            },
        ),
    ]
