"""
Django settings for iluro iluro.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the iluro like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(0%p+1$+^3$3nww@-i^j3*-=k+9gq3&^vfnfinge7@rdxx955='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iluro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iluro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'iluro',
        'USER': 'postgres',
        'PASSWORD': 'Shbi190903',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "ILURO Admin",
    "site_header": "ILURO",
    "site_brand": "ILURO",
    "site_logo_classes": "img-circle",
    "welcome_sign": "ILURO boshqaruv paneli",
    "copyright": "ILURO",
    "search_model": ["auth.User"],
    "topmenu_links": [
        {"name": "Sayt", "url": "index", "permissions": ["auth.view_user"]},
        {"name": "Asosiy bo'limlar", "app": "main"},
        {"name": "Foydalanuvchilar", "model": "auth.User"},
    ],
    "order_with_respect_to": [
        "main",
        "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "main.Subject": "fas fa-book-open",
        "main.Subscription": "fas fa-credit-card",
        "main.Profile": "fas fa-id-badge",
        "main.Test": "fas fa-clipboard-check",
        "main.Question": "fas fa-circle-question",
        "main.Choice": "fas fa-list-ul",
        "main.UserTest": "fas fa-chart-line",
        "main.UserAnswer": "fas fa-square-check",
        "main.Book": "fas fa-file-pdf",
        "main.SubjectSectionEntry": "fas fa-layer-group",
        "main.EssayTopic": "fas fa-pen-nib",
        "main.PracticeSet": "fas fa-shapes",
        "main.PracticeExercise": "fas fa-calculator",
        "main.PracticeChoice": "fas fa-list-check",
        "main.PracticeSetAttempt": "fas fa-chart-column",
        "main.UserPracticeAttempt": "fas fa-square-poll-vertical",
    },
    "custom_css": "css/admin_custom.css",
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "simplex",
    "dark_mode_theme": None,
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "accent": "accent-warning",
    "navbar_small_text": False,
    "sidebar": "sidebar-light-light",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme_colour": "navbar-white",
    "button_classes": {
        "primary": "btn btn-warning",
        "secondary": "btn btn-outline-secondary",
        "info": "btn btn-outline-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-outline-danger",
        "success": "btn btn-outline-success",
    },
}
